theme: jekyll-theme-midnight
title: "The Joy of Coding: Episode Guide"

collections:
  episodes:
    output: true

baseurl: /joy-of-coding-episode-guide

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/
  - miscs/
