theme: jekyll-theme-midnight
title: "The Joy of Coding: Episode Guide"

collections:
  episodes:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "episodes"
    values:
      layout: "episode"

baseurl: /joy-of-coding-episode-guide

keep_files:
  - pagefind

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/
  - miscs/
